### ISSUE TITLE
android_kernel_oneplus_sm8250 repo in disrepair

### ISSUE THREAD

**Issue by pacman366** [OnePlusOSS/android_kernel_4.14_oneplus_mt6877#1]
@OnePlusOSSAdmin  I'm sorry if this is the wrong place to post but I'm not sure where else to go, as this Oneplus repo has a bit more recent activity than the others. It seems [android_kernel_oneplus_sm8250](https://github.com/OnePlusOSS/android_kernel_oneplus_sm8250) repo can use a little care and feeding. Code bases are out of sync with OOS releases, Open issues are left unanswered by maintainers and the sources for the OOS12 branch of the kernel has been missing since its release back in back in January. Can we get some eyes on it? Thanks.

**Comment by OnePlusOSSAdmin** [comment]
It seems the issue has been fixed in android_kernel_oneplus_sm8250 repo. If you find new issue, please open one in that repo, or you could send email to oss@oneplus.com.
