### ISSUE TITLE
Update Kernel source for OnePlus Nord CE 2 

### ISSUE THREAD

**Issue by Notganesh** [OnePlusOSS/android_kernel_4.14_oneplus_mt6877#8]
@OnePlusOSSAdmin @OnePlusOSSAdmin 
When Releasing Latest Kernel source

**Comment by OnePlusOSSAdmin** [comment]
It has been updated, please check.

**Comment by AbzRaider** [comment]
> It has been updated, please check.
Thanks previous source wasn't booting will check about this one

**Comment by Notganesh** [comment]
Let's see boot or not

**Comment by AbzRaider** [comment]
> Let's see boot or not



> Let's see boot or not

I will start fresh this time won't use old commits

**Comment by cherinyy** [comment]
So are you able to close other spam issues?

https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550/issues/6
https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550/issues/7

**Comment by Notganesh** [comment]
L

**Comment by AbzRaider** [comment]
> L

?
